services:
  certbot-web:
    build: .
    image: dpsrv/certbot-web
    container_name: dpsrv-certbot-web
    env_file: ${DPSRV_HOME}/rc/secrets/certbot/certbot.env
    volumes:
      - ${DPSRV_HOME}/srv/www/:/var/www/
      - ${DPSRV_HOME}/rc/secrets/bind:/etc/bind/
      - ${DPSRV_HOME}/rc/secrets/letsencrypt/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    restart: "no"
networks:
  default:
    name: dpsrv
    external: true
